INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product one', 'C1', 19.90, 0, parsedatetime('19-03-2016', 'dd-MM-yyyy'));
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product two', 'C2', 29.90, 0, parsedatetime('29-05-2019', 'dd-MM-yyyy'));
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product three', 'C1', 15.00, 0, null);
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product four', 'C2', 75.50, 1, null);
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product five', 'C3', 19.90, 0, parsedatetime('02-04-2019', 'dd-MM-yyyy'));
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product six', 'C1', 39.90, 0, parsedatetime('30-04-2016', 'dd-MM-yyyy'));
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product seven', 'C4', 44.20, 0, null);
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product eight', 'C1', 77.00, 0, null);
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product nine', 'C3', 23.70, 1, null);
INSERT INTO products (description,category,price,withdrawn,production_date) VALUES ('Product ten', 'C2', 92.20, 0, parsedatetime('30-04-2016', 'dd-MM-yyyy'));